/**
 * @file Version.h
 * @brief Library version information.
 * 
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version in library.json instead.
 * 
 * Generated: 2026-02-28 21:10:01
 * Git commit: a989fce (clean)
 */

#pragma once

#include <stdint.h>

namespace SHT3x {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (new features, backward compatible).
static constexpr uint16_t VERSION_MINOR = 3;

/// @brief Patch version (bug fixes).
static constexpr uint16_t VERSION_PATCH = 2;

/// @brief Full version string (e.g., "1.2.3").
static constexpr const char* VERSION = "1.3.2";

/// @brief Encoded version for numeric comparison.
/// @note Format: MAJOR*10000 + MINOR*100 + PATCH
/// @note Example: version 1.2.3 = 10203
static constexpr uint32_t VERSION_CODE = 10302;

/// @brief Build date (YYYY-MM-DD).
static constexpr const char* BUILD_DATE = "2026-02-28";

/// @brief Build time (HH:MM:SS).
static constexpr const char* BUILD_TIME = "21:10:01";

/// @brief Full build timestamp.
static constexpr const char* BUILD_TIMESTAMP = "2026-02-28 21:10:01";

/// @brief Git commit hash (short).
static constexpr const char* GIT_COMMIT = "a989fce";

/// @brief Git working tree status ("clean" or "dirty").
/// @note "dirty" means there are uncommitted changes.
static constexpr const char* GIT_STATUS = "clean";

/// @brief Full version string with build info.
/// @note Format: "version (commit, date time)"
static constexpr const char* VERSION_FULL = "1.3.2 (a989fce, 2026-02-28 21:10:01)";

}  // namespace SHT3x
